# Generated by Django 3.1.14 on 2023-05-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0002_auto_20230519_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="previous_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pokemon_entities.pokemon",
            ),
        ),
    ]
