# Generated by Django 3.1.14 on 2023-05-19 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0004_auto_20230519_2037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="previous_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_evolutions",
                to="pokemon_entities.pokemon",
            ),
        ),
    ]
