# Generated by Django 3.1.14 on 2023-05-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon_entities", "0005_auto_20230519_2119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="previous_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_evolutions",
                to="pokemon_entities.pokemon",
                verbose_name="Предыдущая эволюция",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="Заголовок на английском",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="Заголовок на японском",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_ru",
            field=models.CharField(
                max_length=20, verbose_name="Заголовок на русском"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время и дата появления"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="defence",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Защита"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Время и дата исчезновения",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="health",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Здоровье"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="latitude",
            field=models.FloatField(max_length=50, verbose_name="Ширина"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="level",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Уровень"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="longitude",
            field=models.FloatField(max_length=50, verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pokemon_entities.pokemon",
                verbose_name="Покемон",
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="stamina",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Выносливость"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="strength",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Сила"
            ),
        ),
    ]
